# HTTP, SOCKS5, SOCKS5-over-TLS 混合端口
mixed-port: 7890
ipv6: true
# 允许局域网连接
allow-lan: true # 允许局域网连接
unified-delay: true
tcp-concurrent: true

# RESTful API
external-controller: "127.0.0.1:9090"
external-ui: "ui"
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist-no-fonts.zip"

# 缓存设置
profile:
  store-selected: true
  store-fake-ip: true

# 日志设置
log-level: warning

# 国内外 DNS 定义
chinaDNS: &chinaDNS ['quic://223.5.5.5', 'tls://119.29.29.29']
chinaDohDNS: &chinaDohDNS ['https://223.5.5.5/dns-query#DIRECT', 'https://1.12.12.12/dns-query#DIRECT']
foreignDNS: &foreignDNS ['https://cloudflare-dns.com/dns-query#proxy', 'https://dns.google/dns-query#proxy&ecs=114.114.114.114/24']

# DNS 设置
dns:
  enable: true
  prefer-h3: true
  enhanced-mode: fake-ip
  cache-algorithm: arc
  # respect-rules: true
  ipv6: true #ipv6默认值false
  use-hosts: true
  use-system-hosts: true
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  # fake-ip-filter-mode: rule
  fake-ip-filter:
    - ".lan"
    - ".local"
    - ".wiwide.com"
    - "captive.apple.com"
    - ".market.xiaomi.com"
    - "rule-set:ads,private"
  # 用于解析其他 DNS 服务器域名，必须是 IP 地址
  default-nameserver: *chinaDNS
  nameserver: *foreignDNS
  nameserver-policy:
    ".lan": "system"
    ".local": "system"
    ".wiwide.com": "system"
    "captive.apple.com": "system"
    ".market.xiaomi.com": "system"
    "rule-set:ads": "rcode://success"
    "rule-set:private,apple_cn,emby,bilibili": "system"
    "rule-set:bank_cn_domain,geolocation-cn": *chinaDNS
    # # 国外域名使用国外 DNS (通过代理)
    # "rule-set:gfw":
    #   - https://dns.google/dns-query#ecs=114.114.114.114/24
    #   - https://cloudflare-dns.com/dns-query
  direct-nameserver: ['system', 'quic://223.5.5.5', 'tls://119.29.29.29']
  direct-nameserver-follow-policy: true
  proxy-server-nameserver: *chinaDohDNS

hosts:
  'cloudflare-dns.com': ['1.1.1.1', '1.0.0.1']
  'dns.google': ['8.8.8.8', '8.8.4.4']

  # 解决谷歌商店无法下载的问题
  'services.googleapis.cn': 'services.googleapis.com'

  # 屏蔽哔哩哔哩PCDN，解决访问视频卡顿/直播问题
  '+.mcdn.bilivideo.com': ['0.0.0.0']
  '+.mcdn.bilivideo.cn': ['0.0.0.0']
  '+.edge.mountaintoys.cn': ['0.0.0.0']
  '+.h2.smtcdns.net': ['0.0.0.0']

ntp:
  enable: true
  write-to-system: false
  server: 'ntp.aliyun.com'
  port: 123
  interval: 60

# TUN 模式设置
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  # route-exclude-address:
  #   - "10.0.0.0/8"
  #   - "100.64.0.0/10"
  #   - "127.0.0.0/8"
  #   - "169.254.0.0/16"
  #   - "172.16.0.0/12"
  #   - "192.0.0.0/24"
  #   - "192.0.2.0/24"
  #   - "192.88.99.0/24"
  #   - "192.168.0.0/16"
  #   - "198.51.100.0/24"
  #   - "203.0.113.0/24"
  #   - "224.0.0.0/4"
  #   - "255.255.255.255/32"

sniffer:
  enable: false
  ## 以下三个值默认true
  # force-dns-mapping: true
  # parse-pure-ip: true
  # override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - ".v2ex.com"
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - ".push.apple.com"
    - ".apple.com"
    - ".wechat.com"
    - ".qpic.cn"
    - ".qq.com"
    - ".wechatapp.com"
    - ".vivox.com"
    # 向日葵服务
    - ".oray.com"
    - ".sunlogin.net"

# ------------------------------------------------- #
#              代理订阅 (Proxy Providers)            #
# ------------------------------------------------- #
PProviders: &PProviders
  type: http
  interval: 86400
  health-check:
    enable: true
    url: "https://www.gstatic.com/generate_204"
    interval: 600
    lazy: true
  filter: "^(?!.*(拒绝|直连|群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|提示|特别|访问|支持|教程|关注|更新|作者|加入|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|traffic))"

proxy-providers:
  yourprovider1:
    <<: *PProviders
    url: "xxx"
    override:
      additional-prefix: "[yourprovider1]"
      # udp: true
  yourprovider2:
    <<: *PProviders
    url: "xxx"
    override:
      additional-prefix: "[yourprovider2]"
      # udp: true
      proxy-name:
        - pattern: "^(.+) - IEPL.+- (.+)$"
          target: "$1-$2"

# ------------------------------------------------- #
#                 代理组 (Proxy Groups)              #
# ------------------------------------------------- #

# 锚点定义区 (Anchors)
# 锚点 - 节点筛选组
FilterHK: &FilterHK '^(?=.*((?i)🇭🇰|香港|(\b(HK|HKG|Hong)(\d+)?\b)))(?!.*((?i)回国|校园|游戏|🎮|(\b(GAME)\b)|([2-9]\.\d+))).*$'
FilterTW: &FilterTW '^(?=.*((?i)🇹🇼|台湾|(\b(TW|TWN|Tai|Taiwan)(\d+)?\b)))(?!.*((?i)回国|校园|游戏|🎮|(\b(GAME)\b)|([2-9]\.\d+))).*$'
FilterJP: &FilterJP '^(?=.*((?i)🇯🇵|日本|川日|东京|大阪|泉日|埼玉|(\b(JP|JPN|Japan)(\d+)?\b)))(?!.*((?i)回国|校园|游戏|🎮|(\b(GAME)\b)|([2-9]\.\d+))).*$'
# FilterKR: &FilterKR '^(?=.*((?i)🇰🇷|韩国|韓|首尔|(\b(KR|KOR|Korea)(\d+)?\b)))(?!.*((?i)回国|校园|游戏|🎮|(\b(GAME)\b)|([2-9]\.\d+))).*$'
FilterSG: &FilterSG '^(?=.*((?i)🇸🇬|新加坡|狮|(\b(SG|SGP|Singapore)(\d+)?\b)))(?!.*((?i)回国|校园|游戏|🎮|(\b(GAME)\b)|([2-9]\.\d+))).*$'
FilterUS: &FilterUS '^(?=.*((?i)🇺🇸|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|(\b(US|USA|United States)(\d+)?\b)))(?!.*((?i)回国|校园|游戏|🎮|(\b(GAME)\b)|([2-9]\.\d+))).*$'
FilterNoCN: &FilterNoCN '^(?=.*(?i)(港|hk|hongkong|Hong Kong|🇭🇰|台|🇹🇼|TW|Taiwan)).*$'

# &BaseProxy: 定义一个基础的策略组选项列表，用于大多数分流规则
BaseProxy:
  &BaseProxy {
    type: select,
    empty-fallback: REJECT,
    proxies: [proxy, DIRECT, REJECT, hk, tw, jp, sg, us, noCN, allproxies],
  }

BaseSmart: &BaseSmart {
    type: url-test,
    interval: 600,
    timeout: 3000,
    tolerance: 50,
    lazy: true,
    url: "https://www.google.com/generate_204",
    hidden: true,
    # uselightgbm: true,
    include-all: true,
    # policy-priority: "element:0.8",
    max-failed-times: 3,
  }
# -------------------------------------------------
proxy-groups:
  # --- 核心选择组 (全部使用锚点，保持一致) ---

  - name: allproxies
    type: select
    include-all: true
    exclude-filter: "(?i)(🟢 直连)"
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Proxy.png


  - name: ai
    <<: *BaseProxy
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/AI.png
    default-selected: us
  - name: telegram
    <<: *BaseProxy
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Telegram.png
  - name: microsoft@cn
    type: select
    proxies:
      - proxy
      - DIRECT
    default-selected: DIRECT
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Microsoft.png
  - name: github
    <<: *BaseProxy
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/GitHub.png
  - name: emby
    <<: *BaseProxy
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Emby.png
  - name: streaming
    <<: *BaseProxy
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Streaming.png

  - name: Speedtest
    type: select
    include-all-providers: true
    proxies: [DIRECT, PASS]
    default-selected: PASS
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Speedtest.png
  - name: proxy
    type: select
    empty-fallback: REJECT
    proxies:
      - hk
      - tw
      - jp
      - sg
      - us
      - noCN
      - allproxies # 全部节点手动
    icon: https://github.com/666OS/YYDS/raw/main/mihomo/image/mihomo.png
  - name: cn
    type: select
    proxies:
      - proxy
      - DIRECT
      - allproxies
    default-selected: DIRECT
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/China.png


  # --- 自动分流组 ---
  - name: noCN
    <<: *BaseSmart
    exclude-filter: *FilterNoCN
  - name: hk
    <<: *BaseSmart
    filter: *FilterHK
  - name: tw
    <<: *BaseSmart
    filter: *FilterTW
  - name: jp
    <<: *BaseSmart
    filter: *FilterJP
  - name: sg
    <<: *BaseSmart
    filter: *FilterSG
  - name: us
    <<: *BaseSmart
    filter: *FilterUS

# ------------------------------------------------- #
#               规则集 (Rule Providers)              #
# ------------------------------------------------- #
rule-anchor:
  ip:
    &ip {
      type: http,
      interval: 86400,
      behavior: ipcidr,
      format: mrs,
      proxy: proxy,
    }
  domain:
    &domain {
      type: http,
      interval: 86400,
      behavior: domain,
      format: mrs,
      proxy: proxy,
    }
rule-providers:
  apple_cn:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"
    path: './ruleset/apple_cn.mrs'
    path-in-bundle: "geo/geosite/apple-cn.mrs"
  cn_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"
    path: './ruleset/cn_ip.mrs'
    path-in-bundle: "geo/geoip/cn.mrs"
  geolocation-cn:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-cn.mrs"
    path: './ruleset/geolocation-cn.mrs'
    path-in-bundle: "geo/geosite/geolocation-cn.mrs"
  netflix_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"
    path: './ruleset/netflix_ip.mrs'
    path-in-bundle: "geo/geoip/netflix.mrs"
  netflix_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"
    path: './ruleset/netflix_domain.mrs'
    path-in-bundle: "geo/geosite/netflix.mrs"
  ai_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs"
    path: './ruleset/ai_domain.mrs'
    path-in-bundle: "geo/geosite/category-ai-!cn.mrs"
  gfw:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"
    path: './ruleset/gfw.mrs'
    path-in-bundle: "geo/geosite/gfw.mrs"
  telegram_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"
    path: './ruleset/telegram_ip.mrs'
    path-in-bundle: "geo/geoip/telegram.mrs"
  telegram_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"
    path: './ruleset/telegram_domain.mrs'
    path-in-bundle: "geo/geosite/telegram.mrs"
  microsoft@cn:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft@cn.mrs"
    path: './ruleset/microsoft@cn.mrs'
    path-in-bundle: "geo/geosite/microsoft@cn.mrs"
  bank_cn_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-bank-cn.mrs"
    path: './ruleset/bank_cn_domain.mrs'
    path-in-bundle: "geo/geosite/category-bank-cn.mrs"
  Speedtest:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-speedtest.mrs"
    path: './ruleset/Speedtest.mrs'
    path-in-bundle: "geo/geosite/category-speedtest.mrs"
  ads:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads@ads.mrs"
    path: './ruleset/ads.mrs'
    path-in-bundle: "geo/geosite/category-ads@ads.mrs"
  private_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"
    path: './ruleset/private_ip.mrs'
    path-in-bundle: "geo/geoip/private.mrs"
  private:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"
    path: './ruleset/private.mrs'
    path-in-bundle: "geo/geosite/private.mrs"
  github:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"
    path: './ruleset/github.mrs'
    path-in-bundle: "geo/geosite/github.mrs"
  emby:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-emby.mrs"
    path: './ruleset/emby.mrs'
    path-in-bundle: "geo/geosite/category-emby.mrs"
  bilibili:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.mrs"
    path: './ruleset/bilibili.mrs'
    path-in-bundle: "geo/geosite/bilibili.mrs"
# ------------------------------------------------- #
#                   规则 (Rules)                     #
# ------------------------------------------------- #
rules:
  # --- Block Trackers, Leaks, and Ads ---
  # Block STUN protocol (WebRTC IP leak)
  - AND,((OR,((DST-PORT,3478),(DST-PORT,5349))),(NOT,((RULE-SET,cn_ip,no-resolve)))),REJECT
  # The following rule blocks UDP traffic on port 443, which is the primary port for QUIC.
  - RULE-SET,private,DIRECT
  - DOMAIN-SUFFIX,wiwide.com,DIRECT
  - DOMAIN,captive.apple.com,DIRECT
  - RULE-SET,private_ip,DIRECT,no-resolve
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,motrix-next-engine,DIRECT
  - PROCESS-NAME,Microsoft Outlook,DIRECT
  - RULE-SET,ads,REJECT

  # --- Rule Set Based Routing ---
  # - RULE-SET,apple_ip,apple,no-resolve
  #  - RULE-SET,apple@cn,apple@cn
  - RULE-SET,ai_domain,ai
  - RULE-SET,telegram_domain,telegram
  - RULE-SET,telegram_ip,telegram,no-resolve
  - RULE-SET,microsoft@cn,microsoft@cn
  - RULE-SET,github,github
  - OR,((RULE-SET,emby),(DOMAIN-KEYWORD,emby.)),emby
  - RULE-SET,netflix_domain,streaming
  - RULE-SET,netflix_ip,streaming,no-resolve
  - DOMAIN,apps.apple.com,proxy
  - RULE-SET,Speedtest,Speedtest
  - RULE-SET,gfw,proxy
  - RULE-SET,apple_cn,cn
  - RULE-SET,geolocation-cn,cn
  - RULE-SET,bank_cn_domain,cn
  - RULE-SET,cn_ip,cn

  # --- Final Match ---
  - MATCH,proxy
